#-------------------------------
# Site Settings
title: Portfolio – Maximilian Matthews
logo: "/images/logo.svg" # You can add own logo. For example '/images/logo.png'.
logo_dark: "/images/logo-dark.svg"
description: Portfolio site for Maximilian Matthews
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    # - title: 'Blog'
      # url: '/blog/'
    - title: 'About'
      url: '/about/'
    # - title: 'Elements'
      # url: '/elements/'


# Call to action button
cta_button:
  enable: true
  cta_button_link: "/contact/"
  cta_button_text: Contact


#-------------------------------
# Author Settings
author:
  author_intro: Hey there, I'm Max!
  author_name: Maximilian Matthews
  author_role: Design Engineer @ Terra API (YC W21)
  author_avatar: /images/01.jpg


#-------------------------------
# Sidebar Section Settings
sidebar:
  sidebar_title: Design Engineering Portfolio # You can add an 'em' element to highlight text.
  sidebar_description: Welcome to my portfolio, thanks for taking a look! You'll find my favourite projects I completed at university and in industry, alongside key skills.


# Social Links
social:
- {icon: "fa-brands fa-linkedin-in", name: "LinkedIn", link: "https://www.linkedin.com/in/maximilian-matthews/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/mlm20"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Projects Settings
projects:
  enable: true
  projects_title: Projects # You can add an 'em' element to highlight text.
  projects_description: Discover my favourite design and engineering projects from university and industry.


#-------------------------------
# Skills Settings
#   -- uses faq template
faq:
  enable: true
  faq_title: Skills # You can add an 'em' element to highlight text.
  faq_description: An overview of key skills developed through study, project work, and extracurricular activities. Click on each to learn more.

faq_items:
  - title: Product & UX Design
    description: Experienced in user research, wireframing, prototyping, and user testing to create intuitive and user-friendly digital products. Skilled in using Figma to create pixel-perfect user interfaces, interaction design, and usability testing.

  - title: Frontend development
    description: Proficient in developing responsive and accessible web applications using HTML, CSS, JavaScript, React, Next.js, and Tailwind CSS. Experienced in working with APIs, databases, and version control systems like Git. Skilled in implementing headless CMS like Strapi to manage dynamic content.

  - title: Innovation and design thinking
    description: Skilled in applying human-centred design methodologies, combining creativity, user needs, and technical functionality to develop innovative solutions. Experienced in using design engineering tools such as prototyping, systems thinking, and stakeholder engagement to create meaningful, validated design outcomes. Confident in translating user insights into product specifications and iterating through the design process, from ideation to prototyping and testing.

  - title: Computer-aided design (CAD)
    description: Experience working in CAD and 3D rendering software incl. SolidWorks, Fusion 360, Adobe Dimension, KeyShot.

  - title: Mechatronics
    description: Proficient in integrating mechanical systems with electronics and software to design, prototype, and control devices. Experienced in circuit design, sensor integration, actuator control, and microcontroller programming using Arduino, PlatformIO, MicroPython, and MATLAB. Skilled in signal processing, feedback control, and real-time programming, with hands-on experience in robotics, including ROS, kinematics, dynamics, and control algorithms.

  - title: Engineering analysis
    description: Proficient conducting engineering simulations in FEA and CFD software to test part durability and simulate mechanical movements. Experience using Ansys Granta for material selection.

  - title: Rapid prototyping
    description: Experienced using the Rapid Prototyping paradigm to build, test, and iterate on physical products using techniques such as 3D printing (FDM and SLA), laser cutting, cardboard, Arduino, foam models, breadboard circuits. Familiar with using Figma to test digital products. 

  - title: Data analysis
    description: Experienced in exploring and analysing small and large datasets using statistical methods and machine learning techniques. Skilled in descriptive and inferential statistics, data visualization, and applying machine learning algorithms like regression and classification. Proficient in using Python libraries incl. scikit-learn, NumPy, Pandas, Matplotlib, SciPy as well as MATLAB to solve practical problems and extract actionable insights from data.

  - title: Adobe Creative Suite and Figma
    description: Experienced using the Adobe Creative Suite incl. Illustrator, InDesign, Photoshop, Lightroom, Premiere Pro, and further software incl. Figma and Microsoft Office. Experienced in UI/UX and interaction design.

  - title: Project management and teamwork
    description: Experienced working in multidisciplinary teams on multiple engineering projects, leading meetings, managing strict deadlines. Proficient using Gantt charts and Jira, and working in Agile teams.

  - title: Languages and citizenship
    description: Bilingual in English and German, and have working proficiency in French. Hold duel British and German (EU) citizenship.




#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: Trusted by <em>Professionals</em> # You can add an 'em' element to highlight text.
  testimonials_description: Join our community of creative professionals where you can develop your talents and reach new heights in design.

testimonial-items:
  - name: Amelia Jones
    image: "/images/client-1.jpg"
    designation : Network Engineer
    content : This product designer is an expert in his field. His ability to understand the needs of clients and create designs that satisfy them is astounding.

  - name: Ethan Robinson
    image: "/images/client-2.jpg"
    designation : Blockchain Developer
    content : Kevin is a true visionary in the field of product design. His ability to think outside the box and push boundaries is what sets him apart from the rest.

  - name: Matthew Garcia
    image: "/images/client-3.jpg"
    designation : IT Support Specialist
    content : I cannot recommend this designer highly enough. Their designs are not only visually stunning but also highly functional, making them perfect for our needs.


#-------------------------------
# Blog Section Settings
blog:
  enable: false
  blog_title: Latest <em>Articles</em> & <em>Publications</em> # You can add an 'em' element to highlight text.
  blog_description: Discover the latest industry news, insights, and trends in a few clicks.

#-------------------------------
# Gallery Settings
gallery:
  enable: true
  gallery_title: About # You can add an 'em' element to highlight text.
  gallery_description: |
    Hey there, I'm Max! I'm an engineering (MEng) graduate from Imperial College London and currently work as Design Engineer at Terra API (YC W21) in London.


    I work at the intersection of engineering and design to conceptualise, design, and ship world-class products that are a joy to use, are technically sound, and solve real problems.


    At Terra most of my time is split between product design and frontend development. I work fully end-to-end, starting by understanding user needs, conceptualising solutions (I'm a big fan of pen and paper), creating pixel-perfect designs in Figma, and finally building and shipping frontend code using Next.js and Tailwind CSS. 


    I graduated with an MEng in Design Engineering from Imperial College. There, I completed 11 team-based and 10 individual engineering and design projects, covering areas including mechanical design (CAD), software development (mostly Web), rapid prototyping (laser cutting, 3D printing, workshop skills, etc.), mechatronics (Esp32, Arduino, etc.), and UX and system design (Figma). 


    At Imperial I was also very active in student life (awarded Union Colours). I was elected President and Events Officer of Imperial's LGBTQ society, leading a 12-member team and running weekly events. I was also head of events and a DJ tutor for Imperial's electronic music society!


    During my degree I did a 6 month internship in Germany at REHAU New Ventures, the corporate venture builder of a €3.4B turnover Mittelstand firm. The work was fully in German and I picked up a bunch of useful venture and entrepreneurship skills.


    tl;dr, I like building cool stuff :)
gallery_images:
  - alt: 'Teamwork'
    url: '/images/profile-01.jpg'
  - alt: 'Profile picture'
    url: '/images/profile-02.jpg'
  - alt: 'Campus'
    url: '/images/profile-03.jpg'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Subscribe to Our <em>Newsletter</em> # You can add an 'em' element to highlight text.
  mailchimp_description: Join now and never miss out on our stuff again. Because you are worth it!
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  email: xwpegzeq # Add your form_id
  description: Don't hesitate to reach out to me for any questions or inquiries, I look forward to connecting with you!
# NOTE
# Baleon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id