#-------------------------------
# Site Settings
title: Portfolio – Maximilian Matthews
logo: "/images/logo.svg" # You can add own logo. For example '/images/logo.png'.
logo_dark: "/images/logo-dark.svg"
description: Portfolio site for Maximilian Matthews
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    # - title: 'Blog'
      # url: '/blog/'
    - title: 'About'
      url: '/about/'
    # - title: 'Elements'
      # url: '/elements/'


# Call to action button
cta_button:
  enable: true
  cta_button_link: "/contact/"
  cta_button_text: Say Hello!


#-------------------------------
# Author Settings
author:
  author_intro: Hey, I’m Maximilian Matthews
  author_name: Maximilian Matthews
  author_role: Imperial College 2024 Engineering Graduate
  author_avatar: /images/01.jpg


#-------------------------------
# Sidebar Section Settings
sidebar:
  sidebar_title: Portfolio Site # You can add an 'em' element to highlight text.
  sidebar_description: Welcome to my portfolio! Here, you'll find a range of projects from both my university studies and industry experience, along with an overview of my key skills and expertise.


# Social Links
social:
- {icon: "fa-brands fa-linkedin-in", name: "LinkedIn", link: "https://www.linkedin.com/in/maximilian-matthews/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/mlm20"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Projects Settings
projects:
  enable: true
  projects_title: Projects # You can add an 'em' element to highlight text.
  projects_description: This is a selection of engineering, design, and business projects completed at university and in industry. These showcase the skills and experience I have developed.


#-------------------------------
# Skills Settings
#   -- uses faq template
faq:
  enable: true
  faq_title: Skills # You can add an 'em' element to highlight text.
  faq_description: An overview of relevant skills – developed through study, project work, and extracurricular activities. Click on each to find out more.

faq_items:
  - title: Computer-aided design (CAD)
    description: Experience working in CAD and 3D rendering software incl. Solidworks, Fusion 360, Adobe Dimension, KeyShot.

  - title: Mechatronics
    description: Proficient in integrating mechanical systems with electronics and software to design, prototype, and control devices. Experienced in circuit design, sensor integration, actuator control, and microcontroller programming using Arduino, PlatformIO, MicroPython, and MATLAB. Skilled in signal processing, feedback control, and real-time programming, with hands-on experience in robotics, including ROS, kinematics, dynamics, and control algorithms.

  - title: Full stack development
    description: Experienced developing web applications on the front and backend, using HTML, CSS, JavaScript, Python, Node.js/Express.js, AWS. Skilled implementing high-level algorithms, developing data structures, reading/writing databases, accessing APIs, asynchronous programming, and developing responsive frontends.

  - title: Adobe Creative Suite and Figma
    description: Experienced using the Adobe Creative Suite incl. Illustrator, InDesign, Photoshop, Lightroom, Premiere Pro, and further software incl. Figma and Microsoft Office. Experienced doing graphic design, document/page layout, and video/image editing.

  - title: Rapid prototyping (RP)
    description: Experienced using the Rapid Prototyping paradigm to build, test, and iterate on physical products using technqiues such as 3D printing (FDM and SLA), laser cutting, cardboard, Arduino, foam models, breadboard circuits. Familar with using Figma to test digital products. 

  - title: Engineering analysis
    description: Proficient conducting engineering simulations in FEA and CFD software to test part durability and simulate mechanical movements. Experience using Ansys Granta for material selection.

  - title: Data analysis
    description: Experienced in exploring and analyzing small and large datasets using statistical methods and machine learning techniques. Skilled in descriptive and inferential statistics, data visualization, and applying machine learning algorithms like regression and classification. Proficient in using Python libraries incl. scikit-learn, NumPy, Pandas, Matplotlib, SciPy as well as MATLAB to solve practical problems and extract actionable insights from data.

  - title: Innovation and design thinking
    description: Skilled in applying human-centered design methodologies, combining creativity, user needs, and technical functionality to develop innovative solutions. Experienced in using design engineering tools such as prototyping, systems thinking, and stakeholder engagement to create meaningful, validated design outcomes. Confident in translating user insights into product specifications and iterating through the design process, from ideation to prototyping and testing.

  - title: Project management and teamwork
    description: Experienced working in multidisciplinary teams on multiple engineering projects, leading meetings, managing strict deadlines. Proficient using Gantt charts and Jira, and working in Agile teams.

  - title: Languages and citizenship
    description: Bilingual in English and German, and have working proficiency in French. Hold duel British and German (EU) citizenship.




#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: Trusted by <em>Professionals</em> # You can add an 'em' element to highlight text.
  testimonials_description: Join our community of creative professionals where you can develop your talents and reach new heights in design.

testimonial-items:
  - name: Amelia Jones
    image: "/images/client-1.jpg"
    designation : Network Engineer
    content : This product designer is an expert in his field. His ability to understand the needs of clients and create designs that satisfy them is astounding.

  - name: Ethan Robinson
    image: "/images/client-2.jpg"
    designation : Blockchain Developer
    content : Kevin is a true visionary in the field of product design. His ability to think outside the box and push boundaries is what sets him apart from the rest.

  - name: Matthew Garcia
    image: "/images/client-3.jpg"
    designation : IT Support Specialist
    content : I cannot recommend this designer highly enough. Their designs are not only visually stunning but also highly functional, making them perfect for our needs.


#-------------------------------
# Blog Section Settings
blog:
  enable: false
  blog_title: Latest <em>Articles</em> & <em>Publications</em> # You can add an 'em' element to highlight text.
  blog_description: Discover the latest industry news, insights, and trends in a few clicks.

#-------------------------------
# Gallery Settings
gallery:
  enable: true
  gallery_title: Profile Summary # You can add an 'em' element to highlight text.
  gallery_description: As an MEng graduate of Imperial College London, my expertise in design engineering allows me to integrate technology, design, and business to create products and technology that solve genuine problems. After graduating in August 2024, I am looking for hardware and software engineering opportunities.
  gallery_caption:

gallery_images:
  - alt: 'Teamwork'
    url: '/images/profile-01.jpg'
  - alt: 'Profile picture'
    url: '/images/profile-02.jpg'
  - alt: 'Campus'
    url: '/images/profile-03.jpg'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Subscribe to Our <em>Newsletter</em> # You can add an 'em' element to highlight text.
  mailchimp_description: Join now and never miss out on our stuff again. Because you are worth it!
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  email: xwpegzeq # Add your form_id
  description: Feel free to reach out to me for any inquiries or collaboration opportunities in design engineering, sustainability, or innovative technology solutions. I look forward to connecting with you!
# NOTE
# Baleon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id